// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mvn_nuts_sampler
arma::mat mvn_nuts_sampler(const arma::vec& mean, const arma::mat& Sigma, int mcmc, double epsin, bool adapting);
RcppExport SEXP _januts_mvn_nuts_sampler(SEXP meanSEXP, SEXP SigmaSEXP, SEXP mcmcSEXP, SEXP epsinSEXP, SEXP adaptingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type mcmc(mcmcSEXP);
    Rcpp::traits::input_parameter< double >::type epsin(epsinSEXP);
    Rcpp::traits::input_parameter< bool >::type adapting(adaptingSEXP);
    rcpp_result_gen = Rcpp::wrap(mvn_nuts_sampler(mean, Sigma, mcmc, epsin, adapting));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_januts_mvn_nuts_sampler", (DL_FUNC) &_januts_mvn_nuts_sampler, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_januts(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
