# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmvn_nuts <- function(mean, Sigma, mcmc = 100L, epsin = 1, adapting = FALSE, max_depth = 7L) {
    .Call(`_januts_rmvn_nuts`, mean, Sigma, mcmc, epsin, adapting, max_depth)
}

rmvn_hmc <- function(mean, Sigma, mcmc = 100L, epsin = 1, adapting = FALSE) {
    .Call(`_januts_rmvn_hmc`, mean, Sigma, mcmc, epsin, adapting)
}

